# -*- coding: utf-8 -*-
"""2023/11/2/2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18mmwoIZd9MHSGZEk8r7HI99gvAlxrSkX
"""

#autor: Diana



def hora_normal(hora_24):


  if hora_24 >= 12:
    return hora_24 - 12
  else:
    return hora_24



def hora_24(hora_normal):

  if hora_normal >= 12:
    return hora_normal + 12
  else:
    return hora_normal


#-----------Despliegue----------------

hora_24 = int(input("Digite la hora sin minutos ni segundos"))

hora_normal = hora_normal(hora_24)
print(f"La hora de 24 horas {hora_24} en hora normal es {hora_normal}")