# -*- coding: utf-8 -*-
"""2023/11/2/6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18mmwoIZd9MHSGZEk8r7HI99gvAlxrSkX
"""

def imprimir_color_amarillo(mensaje):
    """
    https://python-para-impacientes.blogspot.com/2016/09/dar-color-las-salidas-en-la-consola.html
    Función que imprime un mensaje del usuario en color amarillo.
    Cuándo se trata de funciones para manipular el aspecto, es posible permitirles las impresiones internas.
    @param: string      Mensaje del usuario.
    """

    print("\x1b[1;35m" + mensaje)



print(imprimir_color_amarillo("Diana"))