# -*- coding: utf-8 -*-
"""2023/11/2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18mmwoIZd9MHSGZEk8r7HI99gvAlxrSkX
"""

#autor: Diana


def area(a,b): #Función para cálcular el área
  return a * b #retorna el resultado del cálculo
#------Despliegue---------


a = int(input("Digite la base "))#Recibe el valor de la base
b = int(input("Digite la altura "))#Recibe el valor de la altura

c = area(a,b) #Se le agrega el cálculo a una variable
print("El área del cuadrado es:"," ",c)#Imprime la variable