# -*- coding: utf-8 -*-
"""2023/11/2/3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18mmwoIZd9MHSGZEk8r7HI99gvAlxrSkX
"""

#autor: Diana



def conversion_dinero(): #Función para convertir de pesos a dorlares y viceberza
  """
  Función que sirve para convertir de pesos a dolares y viceberza
  @param: real el peso
  @param: tipo dato   que hace
  qreturn   string    descricion

  """

  salida = 0
  tipo = int(input("Ingrese 1 si deseas convertir de pesos a dolares o 2 si deseas convertir de dolares a pesos "))
  dinero = float(input("Ingrese la cantidad de dienero"))
  taza = int(input("Ingrese La taza de cambio"))
  if tipo == 1 :
    salida = dinero / taza

  else :
    salida = dinero * taza

  return salida

print(conversion_dinero(), "Gracias por convertir aquí, que tengas un buen día")