# -*- coding: utf-8 -*-
"""2023/11/2/5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18mmwoIZd9MHSGZEk8r7HI99gvAlxrSkX
"""

#autor: Diana

def menu():

  opc = 1

  while opc != 0:

    opc = int(input("0. Salir  1. Convertir  2. Área de un circulo"))
    if opc == 1:

      print(es_numero(conversion_dinero(), "Gracias por convertir aquí, que tengas un buen día"))

    if opc == 2:
      print("El área del circulo es:"," ",circulo(int(input("Digite el radio "))))#Recibe el valor de la base





def conversion_dinero(): #Función para convertir de pesos a dorlares y viceberza
  """
  Función que sirve para convertir de pesos a dolares y viceberza
  @param: real el peso
  @param: tipo dato   que hace
  qreturn   string    descricion

  """

  salida = 0
  tipo = int(input("Ingrese 1 si deseas convertir de pesos a dolares o 2 si deseas convertir de dolares a pesos "))
  dinero = float(input("Ingrese la cantidad de dienero"))
  taza = int(input("Ingrese La taza de cambio"))
  if tipo == 1 :
    salida = dinero / taza

  else :
    salida = dinero * taza

  return salida

#----------------------------------------------------------------------
#-----------------------------------------------------------------------


def circulo(r): #Función para cálcular el área de un circulo
  salida = 0 #Se inicializa variable
  salida = (r**2) * 3.14 #Se hace el cálculo
  return salida #Retorna el resultado de un número
#-------------Despliegue--------- --

#r = int(input("Digite el radio "))#Recibe el valor de la base


#c = circulo(r) #Se le agrega el cálculo a una variable
#print("El área del circulo es:"," ",c)#Imprime la variable


#-----------------------------------------------------------------------



def es_numero(texto=""):

    """
    Función que devuelve si un texto representa un número o no.
    https://www.w3schools.com/python/ref_string_isnumeric.asp
    -1 para no es número, y 1 para sí es número.
    @param: texto   Representa o no un número, incluso valida el vacío.
    @return: Real   1 o -1.
    """

    salida = conversion_dinero()


    if texto.isnumeric() == False:
        salida = -1

    return salida

#-----------------------------------------------------------------------



print(menu())