# -*- coding: utf-8 -*-
"""2023/11/2/8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18mmwoIZd9MHSGZEk8r7HI99gvAlxrSkX
"""

from IPython.utils.text import string

# -*- coding: utf-8 -*-
"""2023/11/2/4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18mmwoIZd9MHSGZEk8r7HI99gvAlxrSkX
"""

#autor: Diana

def menu():

  opc = 1

  while opc != 0:

    opc = int(input("0. Salir  1. Convertir  2. Área de un circulo"))
    if opc == 1:

      print(conversion_dinero())


    if opc == 2:
      print("El área del circulo es:"," ",circulo(int(input("Digite el radio "))))#Recibe el valor de la base





def conversion_dinero(): #Función para convertir de pesos a dorlares y viceberza
  """
  Función que sirve para convertir de pesos a dolares y viceberza
  @param: real el peso
  @param: tipo dato   que hace
  qreturn   string    descricion

  """

  salida = 0

  tipo = input("Ingrese 1 si deseas convertir de pesos a dolares o 2 si deseas convertir de dolares a pesos ")


  if es_numero(tipo) == 1:
    tipo = int(tipo)
    dinero = int((input("Ingrese la cantidad de dienero")))
    taza = float((input("Ingrese La taza de cambio")))


    if tipo == 1 :
      salida = dinero / taza
      imprimir_color_verde("Gracias por convertir aquí, que tengas un buen día")

    else :
      salida = dinero * taza
      imprimir_color_verde("Gracias por convertir aquí, que tengas un buen día")

  else:
    salida = imprimir_color_amarillo("La opción ingresada no es un número")





  return salida

#----------------------------------------------------------------------
#-----------------------------------------------------------------------


def circulo(r): #Función para cálcular el área de un circulo
  salida = 0 #Se inicializa variable
  salida = (r**2) * 3.14 #Se hace el cálculo
  return salida #Retorna el resultado de un número
#-------------Despliegue--------- --

#r = int(input("Digite el radio "))#Recibe el valor de la base


#c = circulo(r) #Se le agrega el cálculo a una variable
#print("El área del circulo es:"," ",c)#Imprime la variable


#-----------------------------------------------------------------------


#-----------------------------------------------------------------------



def es_numero(texto=""):

    """
    Función que devuelve si un texto representa un número o no.
    https://www.w3schools.com/python/ref_string_isnumeric.asp
    -1 para no es número, y 1 para sí es número.
    @param: texto   Representa o no un número, incluso valida el vacío.
    @return: Real   1 o -1.
    """

    salida = 1


    if texto.isnumeric() == False:
        salida = -1

    return salida

#-----------------------------------------------------------------------


def imprimir_color_amarillo(mensaje):
    """
    https://python-para-impacientes.blogspot.com/2016/09/dar-color-las-salidas-en-la-consola.html
    Función que imprime un mensaje del usuario en color amarillo.
    Cuándo se trata de funciones para manipular el aspecto, es posible permitirles las impresiones internas.
    @param: string      Mensaje del usuario.
    """

    #color = color
    print("\x1b[1;31m" + mensaje)
    #print("\x1b[" + color + "m" + mensaje + "\x1b[0m")



#imprimir_color_amarillo("Diana")

def imprimir_color_verde(mensaje):
    """
    https://python-para-impacientes.blogspot.com/2016/09/dar-color-las-salidas-en-la-consola.html
    Función que imprime un mensaje del usuario en color amarillo.
    Cuándo se trata de funciones para manipular el aspecto, es posible permitirles las impresiones internas.
    @param: string      Mensaje del usuario.
    """

    #color = color
    print("\x1b[1;32m" + mensaje)
    #print("\x1b[" + color + "m" + mensaje + "\x1b[0m")
#-----------------------------------------------------------------------

print(menu())